name: store_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #
  shared_preferences: ^2.2.2  #Para globalizar información entre Widgets
  tflite_flutter: ^0.11.0
  image_picker: ^0.8.8+3       # Para tomar fotos
  image: ^3.1.0               # Para preprocesamiento básico
  flutter_secure_storage: ^9.0.0 #Seguridad de encriptado del usuario
  geolocator: 14.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  #


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.4.0
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/models/plant_disease_model.tflite
    - assets/models/tomato_model_resnet50.tflite

